// Maps FMP's ~130 granular industries onto ~22 GICS-style industry groups.
//
// FMP's own industry taxonomy is too fine-grained to support "~25 large, liquid
// names each" -- only five of its industries contain 25+ US companies above
// $3B market cap. Grouping them restores buckets deep enough to rank within,
// while staying well below sector level (11 buckets) in coarseness.

export const INDUSTRY_GROUPS = {
  'Semiconductors & Equipment': [
    'Semiconductors',
    'Hardware, Equipment & Parts',
  ],
  'Software & IT Services': [
    'Software - Application',
    'Software - Infrastructure',
    'Software - Services',
    'Information Technology Services',
    'Consulting Services',
    'Technology Distributors',
  ],
  'Hardware & Communications Equipment': [
    'Computer Hardware',
    'Communication Equipment',
    'Consumer Electronics',
    'Electronic Gaming & Multimedia',
    'Electrical Equipment & Parts',
  ],
  'Media & Entertainment': [
    'Internet Content & Information',
    'Entertainment',
    'Broadcasting',
    'Publishing',
    'Advertising Agencies',
  ],
  'Telecom & Utilities': [
    'Telecommunications Services',
    'Regulated Electric',
    'Regulated Gas',
    'Regulated Water',
    'Diversified Utilities',
    'Renewable Utilities',
    'Independent Power Producers',
  ],
  'Banks': [
    'Banks - Regional',
    'Banks - Diversified',
    'Financial - Mortgages',
  ],
  'Capital Markets & Asset Management': [
    'Asset Management',
    'Financial - Capital Markets',
    'Financial - Data & Stock Exchanges',
    'Investment - Banking & Investment Services',
    'Financial - Diversified',
    'Shell Companies',
  ],
  'Insurance': [
    'Insurance - Life',
    'Insurance - Property & Casualty',
    'Insurance - Diversified',
    'Insurance - Brokers',
    'Insurance - Specialty',
    'Insurance - Reinsurance',
  ],
  'Consumer Finance & Payments': [
    'Financial - Credit Services',
  ],
  'Real Estate & REITs': [
    'REIT - Specialty',
    'REIT - Retail',
    'REIT - Residential',
    'REIT - Industrial',
    'REIT - Healthcare Facilities',
    'REIT - Diversified',
    'REIT - Office',
    'REIT - Hotel & Motel',
    'REIT - Mortgage',
    'Real Estate - Services',
    'Real Estate - Development',
    'Real Estate - Diversified',
  ],
  'Biotechnology': [
    'Biotechnology',
  ],
  'Pharmaceuticals': [
    'Drug Manufacturers - General',
    'Drug Manufacturers - Specialty & Generic',
    'Medical - Pharmaceuticals',
  ],
  'Medical Devices & Diagnostics': [
    'Medical - Devices',
    'Medical - Instruments & Supplies',
    'Medical - Diagnostics & Research',
    'Medical - Equipment & Services',
    'Medical - Specialties',
  ],
  'Healthcare Providers & Services': [
    'Medical - Healthcare Plans',
    'Medical - Care Facilities',
    'Medical - Healthcare Information Services',
    'Medical - Distribution',
  ],
  'Oil & Gas Producers': [
    'Oil & Gas Exploration & Production',
    'Oil & Gas Integrated',
    'Oil & Gas Drilling',
    'Uranium',
    'Coal',
  ],
  'Energy Services, Midstream & Refining': [
    'Oil & Gas Equipment & Services',
    'Oil & Gas Midstream',
    'Oil & Gas Refining & Marketing',
    'Solar',
  ],
  'Materials & Chemicals': [
    'Chemicals',
    'Chemicals - Specialty',
    'Agricultural Inputs',
    'Steel',
    'Copper',
    'Aluminum',
    'Gold',
    'Silver',
    'Other Precious Metals',
    'Industrial Materials',
    'Construction Materials',
    'Packaging & Containers',
    'Paper, Lumber & Forest Products',
  ],
  'Aerospace, Defense & Machinery': [
    'Aerospace & Defense',
    'Industrial - Machinery',
    'Manufacturing - Tools & Accessories',
    'Manufacturing - Metal Fabrication',
    'Agricultural - Machinery',
    'Conglomerates',
    'Industrial - Infrastructure Operations',
  ],
  'Transportation': [
    'Railroads',
    'Trucking',
    'Integrated Freight & Logistics',
    'Airlines, Airports & Air Services',
    'Marine Shipping',
  ],
  'Commercial & Professional Services': [
    'Specialty Business Services',
    'Staffing & Employment Services',
    'Security & Protection Services',
    'Waste Management',
    'Environmental Services',
    'Engineering & Construction',
    'Construction',
    'Industrial - Distribution',
    'Rental & Leasing Services',
    'Industrial - Pollution & Treatment Controls',
    'Education & Training Services',
  ],
  'Retail & Consumer Services': [
    'Specialty Retail',
    'Discount Stores',
    'Department Stores',
    'Home Improvement',
    'Apparel - Retail',
    'Grocery Stores',
    'Food Distribution',
    'Restaurants',
    'Travel Services',
    'Travel Lodging',
    'Gambling, Resorts & Casinos',
    'Leisure',
    'Auto - Dealerships',
    'Internet Retail',
  ],
  'Consumer Products & Autos': [
    'Auto - Manufacturers',
    'Auto - Parts',
    'Auto - Recreational Vehicles',
    'Apparel - Manufacturers',
    'Apparel - Footwear & Accessories',
    'Luxury Goods',
    'Furnishings, Fixtures & Appliances',
    'Residential Construction',
    'Packaged Foods',
    'Food Confectioners',
    'Agricultural Farm Products',
    'Beverages - Non-Alcoholic',
    'Beverages - Alcoholic',
    'Beverages - Wineries & Distilleries',
    'Tobacco',
    'Household & Personal Products',
    'Personal Products & Services',
  ],
};

// Chip-rail labels. The full names are too long to scan on a phone-width rail,
// so each group also carries an abbreviation used only in the filter chips.
export const SHORT_LABELS = {
  'Semiconductors & Equipment': 'Semis',
  'Software & IT Services': 'Software',
  'Hardware & Communications Equipment': 'Hardware',
  'Media & Entertainment': 'Media',
  'Telecom & Utilities': 'Telecom & Utils',
  'Banks': 'Banks',
  'Capital Markets & Asset Management': 'Capital Markets',
  'Insurance': 'Insurance',
  'Consumer Finance & Payments': 'Consumer Finance',
  'Real Estate & REITs': 'REITs',
  'Biotechnology': 'Biotech',
  'Pharmaceuticals': 'Pharma',
  'Medical Devices & Diagnostics': 'Med Devices',
  'Healthcare Providers & Services': 'Healthcare Svcs',
  'Oil & Gas Producers': 'Oil & Gas',
  'Energy Services, Midstream & Refining': 'Energy Services',
  'Materials & Chemicals': 'Materials',
  'Aerospace, Defense & Machinery': 'Aero & Machinery',
  'Transportation': 'Transport',
  'Commercial & Professional Services': 'Commercial Svcs',
  'Retail & Consumer Services': 'Retail',
  'Consumer Products & Autos': 'Consumer & Autos',
};

const LOOKUP = new Map();
for (const [group, industries] of Object.entries(INDUSTRY_GROUPS)) {
  for (const industry of industries) LOOKUP.set(industry, group);
}

export function groupFor(industry) {
  return LOOKUP.get(industry) ?? null;
}
