/**
 * The app's only view of market data.
 *
 * `market.json` is generated by `npm run data` from real dividend- and
 * split-adjusted end-of-day prices. Nothing here talks to a network or holds a
 * credential: the UI reads a static, deterministic dataset that was built
 * ahead of time.
 */

import dataset from './market.json';
import { momentum12_1, percentileRanks } from '../momentum';
import type { Momentum12_1, Stock, WindowId } from '../types';

/**
 * The 12–1 signal is derived here, once, from the stored adjusted closes.
 * The maths lives in `src/momentum.ts` and is tested against hand-worked
 * examples; this only joins it to the dataset and ranks the field.
 */
function withMomentum(stocks: typeof dataset.stocks): Stock[] {
  const computed = stocks.map((stock) => momentum12_1(stock.history.closes));
  const percentiles = percentileRanks(computed.map((m) => m?.riskAdjusted ?? null));

  return stocks.map((stock, i) => {
    const m = computed[i];
    const momentum: Momentum12_1 | null = m && {
      return12_1: m.return12_1,
      volatility: m.volatility,
      riskAdjusted: m.riskAdjusted,
      percentile: percentiles[i],
      from: stock.history.dates[m.fromIndex],
      to: stock.history.dates[m.toIndex],
    };
    return { ...stock, momentum: momentum ?? null };
  });
}

export const RANKS: Stock[] = withMomentum(dataset.stocks);

/** The most recent close in the dataset, e.g. "2026-08-12". */
export const AS_OF: string = dataset.asOf;

export const SOURCE: string = dataset.source;

export function findStock(symbol: string): Stock | undefined {
  return RANKS.find((stock) => stock.symbol === symbol);
}

/** "2026-08-12" -> "Aug 12". Parsed as a plain date, not a timestamp. */
export function formatAsOf(iso: string): string {
  const [year, month, day] = iso.split('-').map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

/** "2025-08-12" -> "Aug 12, 2025". Used where a year is needed to disambiguate. */
export function formatAsOfLong(iso: string): string {
  const [year, month, day] = iso.split('-').map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  });
}

export const RANKS_SUBTITLE = `Adjusted close · ${formatAsOf(AS_OF)}`;

/** Trading days shown for each graph window. */
const WINDOW_DAYS: Record<WindowId, number> = {
  '1M': 22,
  '3M': 66,
  '6M': 126,
  '1Y': 252,
  '2Y': 504,
};

export const WINDOWS: WindowId[] = ['1M', '3M', '6M', '1Y', '2Y'];
export const DEFAULT_WINDOW: WindowId = '1Y';

/** At most this many points are drawn, whatever the window length. */
const MAX_POINTS = 130;

/**
 * The adjusted closes to draw for one stock over one window: the tail of its
 * history, thinned for drawing but always keeping the latest close.
 */
export function seriesFor(stock: Stock, window: WindowId): number[] {
  const closes = stock.history.closes;
  const slice = closes.slice(Math.max(0, closes.length - WINDOW_DAYS[window]));
  const step = Math.ceil(slice.length / MAX_POINTS);
  if (step <= 1) return slice;

  const points = slice.filter((_, i) => i % step === 0);
  const last = slice[slice.length - 1];
  if (points[points.length - 1] !== last) points.push(last);
  return points;
}

/** The date range actually covered by a window, for labelling. */
export function rangeFor(stock: Stock, window: WindowId): { from: string; to: string } {
  const dates = stock.history.dates;
  const slice = dates.slice(Math.max(0, dates.length - WINDOW_DAYS[window]));
  return { from: slice[0], to: slice[slice.length - 1] };
}
