/**
 * The app's only view of market data.
 *
 * `market.json` is generated by `npm run data` from real dividend- and
 * split-adjusted end-of-day prices. Nothing here talks to a network or holds a
 * credential: the UI reads a static, deterministic dataset that was built
 * ahead of time.
 */

import dataset from './market.json';
import { momentum12_1, momentum6_1, momentumBlend, percentileRanks } from '../momentum';
import type { MomentumWindow, Stock, WindowId } from '../types';
import type { MomentumResult } from '../momentum';

/**
 * The momentum signals are derived here, once, from the stored adjusted
 * closes. The maths lives in `src/momentum.ts` and is tested against
 * hand-worked examples; this only joins it to the dataset, ranks the field,
 * and orders the list by the blend.
 */
type RawStock = (typeof dataset.stocks)[number];

function attach(
  stock: RawStock,
  result: MomentumResult | null,
  percentile: number | null,
): MomentumWindow | null {
  if (!result) return null;
  return {
    totalReturn: result.totalReturn,
    volatility: result.volatility,
    riskAdjusted: result.riskAdjusted,
    percentile,
    from: stock.history.dates[result.fromIndex],
    to: stock.history.dates[result.toIndex],
  };
}

function rankUniverse(stocks: RawStock[]): Stock[] {
  const long = stocks.map((s) => momentum12_1(s.history.closes));
  const short = stocks.map((s) => momentum6_1(s.history.closes));
  const longPct = percentileRanks(long.map((m) => m?.riskAdjusted ?? null));
  const shortPct = percentileRanks(short.map((m) => m?.riskAdjusted ?? null));

  const ranked: Stock[] = stocks.map((stock, i) => ({
    ...stock,
    rank: 0,
    momentum12_1: attach(stock, long[i], longPct[i]),
    momentum6_1: attach(stock, short[i], shortPct[i]),
    blend: momentumBlend(longPct[i], shortPct[i]),
  }));

  // Momentum Blend is the primary ranking value. Anything without one sorts
  // to the bottom, and ties fall back to the symbol so the order is stable.
  ranked.sort((a, b) => {
    const left = a.blend ?? -Infinity;
    const right = b.blend ?? -Infinity;
    if (left !== right) return right - left;
    return a.symbol < b.symbol ? -1 : a.symbol > b.symbol ? 1 : 0;
  });
  ranked.forEach((stock, i) => {
    stock.rank = i + 1;
  });
  return ranked;
}

export const RANKS: Stock[] = rankUniverse(dataset.stocks);

/** The most recent close in the dataset, e.g. "2026-08-12". */
export const AS_OF: string = dataset.asOf;

export const SOURCE: string = dataset.source;

export function findStock(symbol: string): Stock | undefined {
  return RANKS.find((stock) => stock.symbol === symbol);
}

/** "2026-08-12" -> "Aug 12". Parsed as a plain date, not a timestamp. */
export function formatAsOf(iso: string): string {
  const [year, month, day] = iso.split('-').map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  });
}

/** "2025-08-12" -> "Aug 12, 2025". Used where a year is needed to disambiguate. */
export function formatAsOfLong(iso: string): string {
  const [year, month, day] = iso.split('-').map(Number);
  const date = new Date(Date.UTC(year, month - 1, day));
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  });
}

export const RANKS_SUBTITLE = `Momentum blend · ${formatAsOf(AS_OF)}`;

/** Trading days shown for each graph window. */
const WINDOW_DAYS: Record<WindowId, number> = {
  '1M': 22,
  '3M': 66,
  '6M': 126,
  '1Y': 252,
  '2Y': 504,
};

export const WINDOWS: WindowId[] = ['1M', '3M', '6M', '1Y', '2Y'];
export const DEFAULT_WINDOW: WindowId = '1Y';

/** At most this many points are drawn, whatever the window length. */
const MAX_POINTS = 130;

/**
 * The adjusted closes to draw for one stock over one window: the tail of its
 * history, thinned for drawing but always keeping the latest close.
 */
export function seriesFor(stock: Stock, window: WindowId): number[] {
  const closes = stock.history.closes;
  const slice = closes.slice(Math.max(0, closes.length - WINDOW_DAYS[window]));
  const step = Math.ceil(slice.length / MAX_POINTS);
  if (step <= 1) return slice;

  const points = slice.filter((_, i) => i % step === 0);
  const last = slice[slice.length - 1];
  if (points[points.length - 1] !== last) points.push(last);
  return points;
}

/** The date range actually covered by a window, for labelling. */
export function rangeFor(stock: Stock, window: WindowId): { from: string; to: string } {
  const dates = stock.history.dates;
  const slice = dates.slice(Math.max(0, dates.length - WINDOW_DAYS[window]));
  return { from: slice[0], to: slice[slice.length - 1] };
}
